FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/naveenkumarc98/Ansible/refs/heads/main/nginx.yaml /usr/share/nginx/html/index.html
CMD ["nginx", "-g", "daemon off;"]